services:

  # ─── 1. Servidor de Descubrimiento (Eureka) ───────────────────────
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - perutours-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  # ─── 2. API Gateway (único punto de entrada del Frontend) ─────────
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - perutours-net

  # ─── 3. Auth Service (Usuarios y Roles → Neon PostgreSQL) ─────────
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - perutours-net

  # ─── 4. Tour Service (Catálogo de Paquetes → Neon PostgreSQL) ─────
  tour-service:
    build: ./tour-service
    container_name: tour-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - perutours-net

  # ─── 5. Booking Service (Cotizaciones → Neon PostgreSQL) ──────────
  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - perutours-net

networks:
  perutours-net:
    driver: bridge

